### ISSUE TITLE
How to build/compile

### ISSUE THREAD

**Issue by Justinzobel** [fruho/fruhoapp#3]
Please add into a README.md

sudo ./install.sh gives:
cp: cannot stat ‘build/fruhod/linux-x86_64/fruhod.bin’: No such file or directory
cp: cannot stat ‘build/fruho/linux-x86_64/fruho.bin’: No such file or directory
<5>Jul  9 10:56:20 logger: ERROR: Could not locate sysvinit rcN.d directories

So it doesn't work on systemd devices.

./run.sh creates a lib dir but nothing else.

**Comment by baimafeima** [comment]
Has this issue already been addressed?

**Comment by fruho** [comment]
For now building requires sysvinit

**Comment by baimafeima** [comment]
I'd like to have Fruho added to the Solus repositories but it was rejected for failure to work on systemd devices. Could you please address this issue to make it more widely available? Fruho is an otherwise excellent application which deserves much wider usage. I also encourage you to get in touch with the Solus team on the dev tracker: https://dev.solus-project.com/T1503

Solus, like many newer Linux-based distributions and operating systems, relies on systemd. I have also checked with their development team and as systemd is going to stay, I would greatly appreciate efforts on your side to make Fruho compatible. Thank you!

OS: Solus: https://solus-project.com/
